ACCEL_ASCII ""

(asciiHeader
  (asciiVersion 3 0)
  (timeStamp 2025 3 13 17 7 21)
  (program "Protel DXP" "Version 1.0.0.30000")
  (copyright "Copyright © Altium Limited 2015")
  (fileAuthor "")
  (headerString "")
  (fileUnits mil)
  (guidString "{00000000-0000-0000-0000-000000000000}")
)
(library "Library_1"
  (textStyleDef "(Default)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PinStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 91.0)
      (strokeWidth 9.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PartStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(WireStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 60.0)
      (strokeWidth 9.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PortStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 60.0)
      (strokeWidth 9.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(DefaultTTF)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "10pTIMESNEWROMAN"
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontItalic False)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (symbolDef "CMP-157458-000001-1_1_N"
    (originalName "CMP-157458-000001-1_1_N")
    (pin (pinNum 1)  (pt 200 0) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 0) "3" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 0) "LV" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 200 -200) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -200) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -200) "LV1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 3)  (pt 200 -300) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -300) "2" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -300) "LV2" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 4)  (pt 200 -400) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -400) "5" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -400) "LV3" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 5)  (pt 200 -500) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -500) "6" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -500) "LV4" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 6)  (pt 1000 0) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1100 0) "10" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1000 0) "HV" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 7)  (pt 1000 -200) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1100 -200) "12" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1000 -200) "HV1" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 8)  (pt 1000 -300) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1100 -300) "11" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1000 -300) "HV2" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 9)  (pt 1000 -400) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1100 -400) "8" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1000 -400) "HV3" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 10)  (pt 1000 -500) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1100 -500) "7" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1000 -500) "HV4" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 11)  (pt 1000 -700) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1100 -700) "4" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1000 -700) "GND" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 12)  (pt 1000 -800) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1100 -800) "9" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1000 -800) "GND" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 200 -900) (pt 200 100) (width 10) )
    (line (pt 200 -900) (pt 1000 -900) (width 10) )
    (line (pt 200 100) (pt 1000 100) (width 10) )
    (line (pt 1000 100) (pt 1000 -900) (width 10) )
    (attr "RefDes" ""  (pt 200 100) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt 200 -1000) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Logic Function" "Translator"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (symbolDef "+5_1_N"
    (originalName "+5_1_N")
    (pin (pinNum 1)  (pt 100 0) (rotation 180.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt 50 0) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 100 0) "PWR" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 100 -100) (pt 100 100) (width 15) )
    (attr "Type" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "RefDes" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Value" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (symbolDef "GND_1_N"
    (originalName "GND_1_N")
    (pin (pinNum 1)  (pt 100 0) (rotation 180.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt 50 0) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 100 0) "GND" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 110 100) (pt 110 -100) (width 15) )
    (line (pt 140 70) (pt 140 -70) (width 15) )
    (line (pt 170 40) (pt 170 -40) (width 15) )
    (line (pt 200 10) (pt 200 -10) (width 15) )
    (attr "Type" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "RefDes" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Value" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (compDef "CMP-157458-000001-1"
    (originalName "CMP-157458-000001-1")
    (compHeader
      (sourceLibrary "")
      (compType Normal)
      (numPins 12)
      (numParts 1)
      (composition Homogeneous)
      (alts (ieeeAlt False) (deMorganAlt False) )
      (refDesPrefix "U")
    )
    (compPin "3" (pinName "LV") (partNum 1) (symPinNum 1) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "1" (pinName "LV1") (partNum 1) (symPinNum 2) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "2" (pinName "LV2") (partNum 1) (symPinNum 3) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "5" (pinName "LV3") (partNum 1) (symPinNum 4) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "6" (pinName "LV4") (partNum 1) (symPinNum 5) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "10" (pinName "HV") (partNum 1) (symPinNum 6) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "12" (pinName "HV1") (partNum 1) (symPinNum 7) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "11" (pinName "HV2") (partNum 1) (symPinNum 8) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "8" (pinName "HV3") (partNum 1) (symPinNum 9) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "7" (pinName "HV4") (partNum 1) (symPinNum 10) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "4" (pinName "GND") (partNum 1) (symPinNum 11) (gateEq 0) (pinEq 0) (pinType Power) )
    (compPin "9" (pinName "GND") (partNum 1) (symPinNum 12) (gateEq 0) (pinEq 0) (pinType Power) )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "CMP-157458-000001-1_1_N") )
    (attachedPattern (patternNum 1) (patternName "FP-BOB-12009-MFG")
      (numPads 12)
      (padPinMap
        (padNum  3) (compPinRef "3")
        (padNum  1) (compPinRef "1")
        (padNum  2) (compPinRef "2")
        (padNum  5) (compPinRef "5")
        (padNum  6) (compPinRef "6")
        (padNum  10) (compPinRef "10")
        (padNum  12) (compPinRef "12")
        (padNum  11) (compPinRef "11")
        (padNum  8) (compPinRef "8")
        (padNum  7) (compPinRef "7")
        (padNum  4) (compPinRef "4")
        (padNum  9) (compPinRef "9")
      )
    )
  )
  (compDef "+5"
    (originalName "+5")
    (compHeader
      (sourceLibrary "")
      (compType Power)
      (numPins 1)
      (numParts 1)
      (refDesPrefix "P")
    )
    (compPin "1" (pinName "+5") (partNum 1) (symPinNum 1) (gateEq 1) (pinEq 0) (pinType Power))
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "+5_1_N") )
  )
  (compDef "GND"
    (originalName "GND")
    (compHeader
      (sourceLibrary "")
      (compType Power)
      (numPins 1)
      (numParts 1)
      (refDesPrefix "P")
    )
    (compPin "1" (pinName "GND") (partNum 1) (symPinNum 1) (gateEq 1) (pinEq 0) (pinType Power))
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "GND_1_N") )
  )
)

(netlist "Netlist_1"
  (compInst "IC1"
    (compRef "ESP32-WROOM-DA-N16")
    (originalName "ESP32-WROOM-DA-N16")
    (patternName "ESP32WROOMDAN16")
    (attr "Arrow Part Number" "" (pt -20 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Arrow Price/Stock" "" (pt -20 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Datasheet Link" "https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjogI6O69X0AhUU5eAKHZraCUwQFnoECCwQAQ&url=https%3A%2F%2Fwww.espressif.com%2Fsites%2Fdefault%2Ffiles%2Fdocumentation%2Fesp32-wroom-da_datasheet_en.pdf&usg=AOvVaw3br5-hykUip-1hiXiLK1oZ" (pt -20 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Height" "3.65mm" (pt -20 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Manufacturer_Name" "Espressif Systems" (pt -20 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Manufacturer_Part_F7" "ESP32-WROOM-DA-N16" (pt -20 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Mouser Part Number" "356-ESP32-WROOMDAN16" (pt -20 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Mouser Price/Stock" "https://www.mouser.co.uk/ProductDetail/Espressif-Systems/ESP32-WROOM-DA-N16?qs=A6eO%252BMLsxmTVM%252Ba16pxmOw%3D%3D" (pt -20 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "MD1"
    (compRef "CMP-157458-000001-1")
    (originalName "CMP-157458-000001-1")
    (patternName "FP-BOB-12009-MFG")
    (attr "Logic Function" "Translator" (pt -20 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "PP51"
    (compRef "+5")
    (originalName "+5")
  )
  (compInst "GND1"
    (compRef "GND")
    (originalName "GND")
  )
  (net "+5"
    (node "MD1" "10")
    (node "PP51" "1")
  )
  (net "GND"
    (node "IC1" "1")
    (node "GND1" "1")
  )
  (net "NetIC1_2"
    (node "IC1" "2")
    (node "MD1" "3")
  )
  (net "NetIC1_37"
    (node "IC1" "37")
    (node "MD1" "1")
  )
  (net "NetMD1_12"
    (node "MD1" "12")
  )
)

(schematicDesign "SchDesign_1"
  (schDesignHeader
    (workspaceSize 11500 7600)
    (gridDfns
      (grid "100mil")
    )
    (designInfo
      (fieldSet "(Default)"
        (fieldDef "Time" "")
        (fieldDef "Date" "")
        (fieldDef "Approved By" "")
        (fieldDef "Checked By" "")
        (fieldDef "Author" "")
        (fieldDef "Company Name" "")
        (fieldDef "Drawn By" "Mangelschots Emiel")
        (fieldDef "Engineer" "")
        (fieldDef "Organization" "")
        (fieldDef "Address1" "")
        (fieldDef "Address2" "")
        (fieldDef "Address3" "")
        (fieldDef "Address4" "")
        (fieldDef "Title" "Aansluitingschema 1 Sensor")
        (fieldDef "Drawing Number" "")
        (fieldDef "Revision" "1.0")
        (fieldDef "Rule" "")
        (fieldDef "ImagePath" "")
        (fieldDef "ProjectName" "")
        (fieldDef "Application_BuildNumber" "")
      )
    )
    (refPointSize 100)
    (infoPointSize 100)
    (junctionSize 20)
    (refPointSizePrint 100)
    (infoPointSizePrint 100)
    (junctionSizePrint 20)
  )

  (sheet "Bodemsensor" (sheetNum 1)
    (titleSheet ""
      1.0000
      (isVisible True)
      (offset 0.0 0.0)
      (border
        (isVisible True)
        (height 7600)
        (width 11500)
        (offset 0 0)
      )
      (zones
        (isVisible True)
        (textStyleRef "(Default)")
        (horizontalZones 4
          (numDirection ascending)
          (numType Alphabetic)
        )
        (verticalZones 4
          (numDirection ascending)
          (numType Numeric)
        )
      )
    )
    (fieldSetRef "(Default)")
    (wire (line (pt 7700 5000) (pt 8000 5000) (width 10) (netNameRef "NetMD1_12") )
    )
    (wire (line (pt 4700 3500) (pt 6200 3500) (width 10) (netNameRef "NetIC1_37") )
    )
    (wire (line (pt 6200 3500) (pt 6200 5000) (width 10) (netNameRef "NetIC1_37") )
    )
    (wire (line (pt 6200 5000) (pt 6500 5000) (width 10) (netNameRef "NetIC1_37") )
    )
    (wire (line (pt 3200 4500) (pt 2900 4500) (width 10) (netNameRef "NetIC1_2") )
    )
    (wire (line (pt 2900 4500) (pt 2900 5200) (width 10) (netNameRef "NetIC1_2") )
    )
    (wire (line (pt 2900 5200) (pt 6500 5200) (width 10) (netNameRef "NetIC1_2") )
    )
    (wire (line (pt 2300 4600) (pt 2500 4600) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 2500 4600) (pt 3200 4600) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 2500 4600) (pt 2500 4900) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 8900 4800) (pt 9500 4800) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 9100 5500) (pt 9100 5200) (width 10) (netNameRef "+5") )
    )
    (wire (line (pt 9100 5200) (pt 7700 5200) (width 10) (netNameRef "+5") )
    )
    (wire (line (pt 9100 5200) (pt 9100 4900) (width 10) (netNameRef "+5") )
    )
    (wire (line (pt 9100 4900) (pt 8900 4900) (width 10) (netNameRef "+5") )
    )
    (port (pt 8000 5000) (portType NoAngle_Dbl_Horz) (portPinLength PortPinLong) (netNameRef "NetMD1_12")  )
    (port (pt 2500 4900) (portType NoAngle_Dbl_Horz) (portPinLength PortPinLong) (netNameRef "GND") (rotation 90.0)  )
    (port (pt 9500 4800) (portType NoAngle_Dbl_Horz) (portPinLength PortPinLong) (netNameRef "GND")  )
    (port (pt 8900 4800) (portType NoAngle_Dbl_Horz) (portPinLength PortPinLong) (netNameRef "GND") (isFlipped True)  )
    (port (pt 8900 4900) (portType NoAngle_Dbl_Horz) (portPinLength PortPinLong) (netNameRef "+5") (isFlipped True)  )
    (symbol (symbolRef "ESP32-WROOM-DA-N16_1_N") (refDesRef "IC1") (partNum 1) (pt 3200 4600)
      (attr "RefDes" "IC1" (pt 200 100) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Datasheet Link" "https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjogI6O69X0AhUU5eAKHZraCUwQFnoECCwQAQ&url=https%3A%2F%2Fwww.espressif.com%2Fsites%2Fdefault%2Ffiles%2Fdocumentation%2Fesp32-wroom-da_datasheet_en.pdf&usg=AOvVaw3br5-hykUip-1hiXiLK1oZ" (pt -20 100) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Height" "3.65mm" (pt -20 100) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Manufacturer_Name" "Espressif Systems" (pt -20 100) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Manufacturer_Part_F7" "ESP32-WROOM-DA-N16" (pt -20 100) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Mouser Part Number" "356-ESP32-WROOMDAN16" (pt -20 100) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Mouser Price/Stock" "https://www.mouser.co.uk/ProductDetail/Espressif-Systems/ESP32-WROOM-DA-N16?qs=A6eO%252BMLsxmTVM%252Ba16pxmOw%3D%3D" (pt -20 100) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "ESP32-WROOM-DA-N16" (pt 200 -2600) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "CMP-157458-000001-1_1_N") (refDesRef "MD1") (partNum 1) (pt 6500 5200)
      (attr "RefDes" "MD1" (pt 200 100) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Logic Function" "Translator" (pt -20 100) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "BOB-12009" (pt 200 -1000) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "+5_1_N") (refDesRef "PP51") (partNum 1) (pt 9100 5500) (rotation 90.0) )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND1") (partNum 1) (pt 2300 4600) (rotation 180.0) )
    (field "Title" (pt 8000 800)  (textStyleRef "10pTIMESNEWROMAN") )
    (field "Revision" (pt 10400 500)  (textStyleRef "10pTIMESNEWROMAN") )
    (field "Drawn By" (pt 10300 200)  (textStyleRef "10pTIMESNEWROMAN") )
  )
  (schematicPrintSettings
    (sheetList
      (sheetRef 2)
    )
  )
  (programState
    (gridState
      (currentAbsGrid "100mil")
      (currentRelGrid "100mil")
      (isAbsoluteGrid True)
      (isDottedGrid True)
      (isVisibleGrid True)
      (isPromptForRel False)
    )
    (ecoState (ecoRecording False))
    (currentTextStyle "(Default)")
  )
)
